version: "2.1"
services:
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./.docker-data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4.8.0
    links:
      - postgres:db
    ports:
      - 8080:8080
